parameters:
- name: myStringName
  type: string
  default: a string value
variables:
- name: one
  value: initialValue

steps:
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo ${one}