parameters:
- name: myString
  type: string
  default: a string value
variables:
- name: one
  value: initialValue

steps:
- script: |
    echo variable one $[ variables.one ]
    echo parameter myString ${{parameters.myString}}